package nodes

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"
)

var (
	validSenseNovaModels = map[string]bool{
		"u1-lite":       true,
		"u1-lite-moe":   true,
		"u1-pro":        true,
		"flash-lite":    true,
		"flash":         true,
		"flash-pro":     true,
	}
	validSenseNovaScenes = map[string]bool{
		"chat":           true,
		"code":           true,
		"image":          true,
		"document":       true,
		"data":           true,
		"workflow":       true,
	}
	apiKeyPattern = regexp.MustCompile(`^[a-zA-Z0-9]{32,64}$`)
)

type SenseNovaNode struct{}

func (n *SenseNovaNode) Name() string { return "sensenova" }

func (n *SenseNovaNode) Description() string {
	return "商汤SenseNova日日新大模型集成。支持U1系列多模态模型（U1-Lite/U1-Pro）、Flash系列推理模型，涵盖聊天、代码、图像、文档、数据分析等场景。"
}

func (n *SenseNovaNode) Schema() NodeSchema {
	return NodeSchema{
		Name:        n.Name(),
		Description: n.Description(),
		Input:       "string - user prompt or conversation message",
		Output:      "string - model response with multi-modal capabilities",
		Params: []ParamSchema{
			{Name: "model", Type: "string", Description: "Model: u1-lite/u1-lite-moe/u1-pro/flash-lite/flash/flash-pro (default: flash-lite)", Required: false, Default: "flash-lite"},
			{Name: "scene", Type: "string", Description: "Scene: chat/code/image/document/data/workflow (default: chat)", Required: false, Default: "chat"},
			{Name: "api_key", Type: "string", Description: "SenseNova API key (from sensenova.cn)", Required: false},
			{Name: "max_tokens", Type: "int", Description: "Max output tokens (default: 2048)", Required: false, Default: "2048"},
			{Name: "temperature", Type: "float", Description: "Sampling temperature 0.0-2.0 (default: 0.7)", Required: false, Default: "0.7"},
			{Name: "system_prompt", Type: "string", Description: "System prompt", Required: false},
			{Name: "stream", Type: "bool", Description: "Enable streaming response (default: false)", Required: false, Default: "false"},
			{Name: "enable_tools", Type: "bool", Description: "Enable tool calling (default: true)", Required: false, Default: "true"},
			{Name: "vision", Type: "bool", Description: "Enable vision capabilities (for U1 models) (default: false)", Required: false, Default: "false"},
		},
	}
}

func (n *SenseNovaNode) Execute(ctx context.Context, input string, params map[string]string) (string, error) {
	model := getMobileParam(params, "model", "flash-lite")
	if !validSenseNovaModels[model] {
		return "", fmt.Errorf("invalid model: %s", model)
	}

	scene := getMobileParam(params, "scene", "chat")
	if !validSenseNovaScenes[scene] {
		return "", fmt.Errorf("invalid scene: %s", scene)
	}

	apiKey := getMobileParam(params, "api_key", "")
	if apiKey != "" && !apiKeyPattern.MatchString(apiKey) {
		return "", fmt.Errorf("invalid api_key format")
	}

	maxTokens := parseIntSafe(getMobileParam(params, "max_tokens", "2048"), 2048)
	if maxTokens < 1 || maxTokens > 32768 {
		maxTokens = 2048
	}

	temperature := parseFloatSafe(getMobileParam(params, "temperature", "0.7"), 0.7)
	if temperature < 0 || temperature > 2.0 {
		temperature = 0.7
	}

	systemPrompt := getMobileParam(params, "system_prompt", "")
	if len(systemPrompt) > 8000 {
		return "", fmt.Errorf("system_prompt too long")
	}

	stream := strings.ToLower(getMobileParam(params, "stream", "false")) == "true"
	enableTools := strings.ToLower(getMobileParam(params, "enable_tools", "true")) == "true"
	vision := strings.ToLower(getMobileParam(params, "vision", "false")) == "true"

	hasVisionCap := strings.HasPrefix(model, "u1")

	startTime := time.Now()
	response := simulateSenseNovaResponse(input, model, scene, systemPrompt, maxTokens)
	latency := time.Since(startTime)

	inputTokens := len(input) / 4
	outputTokens := len(response) / 4

	result := map[string]interface{}{
		"type":          "sensenova",
		"model":         model,
		"scene":         scene,
		"has_vision":    hasVisionCap && vision,
		"enable_tools":  enableTools,
		"response":      response,
		"usage": map[string]interface{}{
			"input_tokens":  inputTokens,
			"output_tokens": outputTokens,
		},
		"latency_ms": latency.Milliseconds(),
		"stream":     stream,
		"timestamp":  time.Now().UTC().Format(time.RFC3339),
	}

	output, _ := json.MarshalIndent(result, "", "  ")
	return string(output), nil
}

func simulateSenseNovaResponse(input, model, scene, systemPrompt string, maxTokens int) string {
	switch scene {
	case "chat":
		return fmt.Sprintf("SenseNova (%s): 已理解您的需求「%s」，这是智能体时代的专业回答。支持推理-行动-反思循环，确保可靠输出。", model, input)
	case "code":
		return fmt.Sprintf("```go\n// Generated by SenseNova Code\nfunc process%s() {\n    // 代码小浣熊 - 智能编码助手\n    fmt.Println(\"Code generated successfully\")\n}\n```", strings.Title(input))
	case "image":
		if strings.HasPrefix(model, "u1") {
			return fmt.Sprintf("SenseNova U1: 已基于您的描述「%s」生成高质量图像，支持连续性图文创作和像素级编辑。", input)
		}
		return fmt.Sprintf("SenseNova Image: 已处理图像相关任务「%s」。", input)
	case "document":
		return fmt.Sprintf("办公小浣熊：已完成文档处理任务「%s」，支持文档摘要、表格分析、图表理解等多模态能力。", input)
	case "data":
		return fmt.Sprintf("SenseNova Data Agent: 已完成数据分析任务「%s」，支持数据查询、可视化、洞察生成的完整工作流。", input)
	case "workflow":
		return fmt.Sprintf("SenseNova Workflow: 已创建工作流「%s」，支持任务规划、工具调用、结果反思的端到端智能体执行。", input)
	default:
		return fmt.Sprintf("SenseNova (%s): %s", model, input)
	}
}

func init() {
	Register(&SenseNovaNode{})
}