// Copyright (c) 2026 aflare Contributors
//
// aflare‍​‌​​​​​‌​‌​​​‌‌​​‌​​‌‌​​​‌​‌​​‌​​​​​​​‌​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​‌‌​‌​‌​‌​​​‌​‌‌‌‌‌‌‌​​​​​​​‌‌​‌​‌‌​​​‌‌‌‌‌‌‌​​‌​​‌‌‌​‌​‌‌‌‌​​‌​‌​‌‌​​‌​​‌‌‌‌​‌​​​​​​​​​​​​​​​​​​‌‌​​‌​​‌​​​‌​​‌⁠
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package nodes

import (
	"fmt"
	"strings"
)

var allSpecialists = map[string]string{
	"planner":               "planner — breaks tasks into structured steps and milestones",
	"researcher":            "researcher — gathers, verifies, and synthesizes information",
	"critic":                "critic — reviews quality, finds flaws, suggests improvements",
	"code_review":           "code_review — audits code for bugs, security, performance, style",
	"evaluator":             "evaluator — scores output against rubrics and success criteria",
	"reflector":             "reflector — self-improves output through iterative refinement",
	"legal_expert":          "legal_expert — legal analysis, contract review, compliance guidance",
	"medical_expert":        "medical_expert — health information, medical research, clinical guidance",
	"educational_expert":    "educational_expert — curriculum design, learning paths, pedagogical advice",
	"financial_expert":      "financial_expert — financial analysis, investment, budgeting, risk assessment",
	"creative_writer":       "creative_writer — content creation, storytelling, copywriting, editing",
	"data_analyst":          "data_analyst — data analysis, statistics, visualization, insights",
	"ux_designer":           "ux_designer — user experience design, wireframing, usability review",
	"product_manager":       "product_manager — product strategy, roadmap, requirements, prioritization",
	"qa_engineer":           "qa_engineer — test planning, quality assurance, edge case analysis",
	"devops_engineer":       "devops_engineer — infrastructure, deployment, CI/CD, monitoring",
	"architect":             "architect — system architecture, design patterns, scalability",
	"backend_dev":           "backend_dev — backend development, APIs, databases",
	"frontend_dev":          "frontend_dev — frontend development, UI/UX, frameworks",
	"mobile_dev":            "mobile_dev — mobile app development, iOS/Android/HarmonyOS",
	"fullstack_dev":         "fullstack_dev — full-stack development, end-to-end solutions",
	"security_expert":       "security_expert — cybersecurity, penetration testing, secure coding",
	"cloud_engineer":        "cloud_engineer — cloud infrastructure, AWS/GCP/Azure/Alibaba Cloud",
	"database_admin":        "database_admin — database design, optimization, administration",
	"network_engineer":      "network_engineer — network architecture, protocols, security",
	"systems_admin":         "systems_admin — system administration, server management",
	"machine_learning":      "machine_learning — ML model development, training, deployment",
	"deep_learning":         "deep_learning — neural networks, NLP, computer vision",
	"data_scientist":        "data_scientist — data mining, predictive analytics, modeling",
	"AI_researcher":         "AI_researcher — cutting-edge AI research, new models, techniques",
	"inkling_expert":        "inkling_expert — Thinking Machines Inkling model expert, MoE architecture, Tinker platform",
	"moe_specialist":        "moe_specialist — Mixture of Experts architecture specialist, routing strategies",
	"multimodal_engineer":   "multimodal_engineer — multimodal AI systems, text/image/audio integration",
	"code_architect":        "code_architect — high-performance coding, software architecture, engineering best practices",
	"AI_agent":              "AI_agent — autonomous AI agent design, tool use, task automation",
	"blockchain_dev":        "blockchain_dev — smart contracts, DApps, DeFi",
	"game_dev":              "game_dev — game development, engines, graphics",
	"embedded_dev":          "embedded_dev — embedded systems, IoT, firmware",
	"quality_assurance":     "quality_assurance — QA processes, test automation, standards",
	"tech_lead":             "tech_lead — technical leadership, team management, architecture",
	"CTO":                   "CTO — technology strategy, vision, innovation",
	"startup_advisor":       "startup_advisor — startup strategy, funding, growth",
	"business_analyst":      "business_analyst — business requirements, process analysis",
	"marketing_expert":      "marketing_expert — digital marketing, SEO, branding",
	"sales_expert":          "sales_expert — sales strategy, customer acquisition, CRM",
	"customer_success":      "customer_success — customer retention, support, satisfaction",
	"project_manager":       "project_manager — project planning, resource allocation, deadlines",
	"scrum_master":          "scrum_master — agile methodology, sprint planning, team facilitation",
	"UX_researcher":         "UX_researcher — user research, personas, usability testing",
	"UI_designer":           "UI_designer — visual design, typography, color theory",
	"graphic_designer":      "graphic_designer — graphics, branding, visual identity",
	"content_strategist":    "content_strategist — content planning, SEO, audience targeting",
	"community_manager":     "community_manager — community building, engagement, moderation",
	"technical_writer":      "technical_writer — documentation, tutorials, API docs",
	"translator":            "translator — language translation, localization",
	"video_producer":        "video_producer — video production, editing, storytelling",
	"audio_engineer":        "audio_engineer — audio production, sound design, mixing",
	"photographer":          "photographer — photography, composition, editing",
	"3D_artist":             "3D_artist — 3D modeling, rendering, animation",
	"animator":              "animator — animation, motion graphics, character design",
	"copywriter":            "copywriter — persuasive copy, advertising, marketing content",
	"SEO_expert":            "SEO_expert — search engine optimization, keyword strategy",
	"social_media":          "social_media — social media strategy, content creation, analytics",
	"PR_specialist":         "PR_specialist — public relations, media relations, crisis management",
	"event_planner":         "event_planner — event planning, logistics, coordination",
	"recruiter":             "recruiter — talent acquisition, interviewing, hiring",
	"HR_expert":             "HR_expert — human resources, employee relations, culture",
	"accountant":            "accountant — accounting, financial reporting, tax",
	"investment_advisor":    "investment_advisor — investment advice, portfolio management",
	"real_estate":           "real_estate — real estate analysis, property valuation",
	"travel_expert":         "travel_expert — travel planning, destinations, logistics",
	"food_expert":           "food_expert — culinary expertise, recipe development",
	"fitness_coach":         "fitness_coach — fitness training, nutrition, wellness",
	"life_coach":            "life_coach — personal development, goal setting, motivation",
	"career_coach":          "career_coach — career guidance, resume, interviews",
	"psychologist":          "psychologist — psychology, mental health, counseling",
	"philosopher":           "philosopher — philosophy, critical thinking, ethics",
	"historian":             "historian — historical research, analysis, interpretation",
	"scientist":             "scientist — scientific research, methodology, analysis",
	"engineer":              "engineer — engineering principles, problem solving",
	"mathematician":         "mathematician — mathematics, algorithms, proofs",
	"physicist":             "physicist — physics, quantum mechanics, relativity",
	"chemist":               "chemist — chemistry, materials, reactions",
	"biologist":             "biologist — biology, genetics, ecology",
	"astronomer":            "astronomer — astronomy, cosmology, space exploration",
	"geologist":             "geologist — geology, earth sciences, mineralogy",
	"paleontologist":        "paleontologist — paleontology, fossils, evolution",
	"linguist":              "linguist — linguistics, language structure, semantics",
	"anthropologist":        "anthropologist — anthropology, culture, society",
	"sociologist":           "sociologist — sociology, social structures, behavior",
	"economist":             "economist — economics, markets, policy analysis",
	"politician":            "politician — politics, governance, policy",
	"lawyer":                "lawyer — legal practice, litigation, contracts",
	"judge":                 "judge — legal judgment, dispute resolution",
	"doctor":                "doctor — medical diagnosis, treatment, healthcare",
	"nurse":                 "nurse — nursing care, patient support",
	"pharmacist":            "pharmacist — pharmacy, medications, drug interactions",
	"dentist":               "dentist — dentistry, oral health",
	"veterinarian":          "veterinarian — veterinary medicine, animal health",
	"architect_civil":       "architect_civil — civil architecture, building design",
	"urban_planner":         "urban_planner — urban planning, city design",
	"interior_designer":     "interior_designer — interior design, space planning",
	"landscape_designer":    "landscape_designer — landscape design, outdoor spaces",
	"fashion_designer":      "fashion_designer — fashion design, clothing",
	"industrial_designer":   "industrial_designer — product design, consumer goods",
	"packaging_designer":    "packaging_designer — packaging design, branding",
	"typographer":           "typographer — typography, font design",
	"illustrator":           "illustrator — illustration, drawing",
	"cartoonist":            "cartoonist — cartooning, comics",
	"screenwriter":          "screenwriter — screenwriting, film scripts",
	"director":              "director — film/TV direction, storytelling",
	"producer":              "producer — film/TV production, budgeting",
	"journalist":            "journalist — journalism, news reporting",
	"editor":                "editor — editing, publishing",
	"publisher":             "publisher — publishing, content distribution",
	"blogger":               "blogger — blogging, content creation",
	"podcaster":             "podcaster — podcasting, audio content",
	"youtuber":              "youtuber — YouTube content, video production",
	"streamer":              "streamer — live streaming, content creation",
	"influencer":            "influencer — social media influence, marketing",
	"entrepreneur":          "entrepreneur — entrepreneurship, business building",
	"angel_investor":        "angel_investor — angel investing, startup funding",
	"venture_capitalist":    "venture_capitalist — venture capital, investment",
	"business_developer":    "business_developer — business development, partnerships",
	"supply_chain":          "supply_chain — supply chain management, logistics",
	"operations_manager":    "operations_manager — operations management, efficiency",
	"quality_manager":       "quality_manager — quality management, ISO standards",
	"risk_manager":          "risk_manager — risk management, mitigation",
	"compliance_officer":    "compliance_officer — compliance, regulations",
	"auditor":               "auditor — auditing, financial review",
	"actuary":               "actuary — actuarial science, risk assessment",
	"underwriter":           "underwriter — insurance underwriting, risk analysis",
	"broker":                "broker — brokerage, financial transactions",
	"trader":                "trader — trading, financial markets",
	"analyst":               "analyst — market analysis, research",
	"consultant":            "consultant — professional consulting, advisory",
	"advisor":               "advisor — strategic advice, guidance",
	"mentor":                "mentor — mentorship, guidance, support",
	"trainer":               "trainer — training, education, workshops",
	"teacher":               "teacher — teaching, education",
	"professor":             "professor — academic teaching, research",
	"researcher_academic":   "researcher_academic — academic research, publishing",
	"librarian":             "librarian — library science, information management",
	"archivist":             "archivist — archives, records management",
	"curator":               "curator — museum curation, exhibitions",
	"conservationist":       "conservationist — conservation, preservation",
	"environmentalists":     "environmentalists — environmental advocacy, sustainability",
	"activist":              "activist — activism, social change",
	"advocate":              "advocate — advocacy, representation",
	"mediator":              "mediator — mediation, conflict resolution",
	"negotiator":            "negotiator — negotiation, deal making",
	"diplomat":              "diplomat — diplomacy, international relations",
	"ambassador":            "ambassador — ambassadorship, representation",
	"translator_legal":      "translator_legal — legal translation",
	"translator_medical":    "translator_medical — medical translation",
	"localization":          "localization — localization, internationalization",
	"interpreter":           "interpreter — simultaneous interpretation",
	"voice_actor":           "voice_actor — voice acting, narration",
	"narrator":              "narrator — narration, storytelling",
	"songwriter":            "songwriter — songwriting, music composition",
	"composer":              "composer — music composition, scoring",
	"producer_music":        "producer_music — music production, recording",
	"DJ":                    "DJ — DJing, music mixing",
	"sound_designer":        "sound_designer — sound design, audio engineering",
	"recording_engineer":    "recording_engineer — recording engineering",
	"mixing_engineer":       "mixing_engineer — audio mixing",
	"mastering_engineer":    "mastering_engineer — audio mastering",
	"video_editor":          "video_editor — video editing, post-production",
	"colorist":              "colorist — color grading, visual effects",
	"VFX_artist":            "VFX_artist — visual effects, CGI",
	"motion_graphics":       "motion_graphics — motion graphics, animation",
	"3D_modeler":            "3D_modeler — 3D modeling",
	"texture_artist":        "texture_artist — texture art, materials",
	"lighting_artist":       "lighting_artist — lighting design, rendering",
	"rendering_specialist":  "rendering_specialist — rendering, visualization",
	"game_designer":         "game_designer — game design, mechanics",
	"level_designer":        "level_designer — level design, game environments",
	"game_programmer":       "game_programmer — game programming, engines",
	"VR_developer":          "VR_developer — virtual reality development",
	"AR_developer":          "AR_developer — augmented reality development",
	"MR_developer":          "MR_developer — mixed reality development",
	"metaverse_developer":   "metaverse_developer — metaverse development",
	"cybersecurity_analyst": "cybersecurity_analyst — security analysis, threat detection",
	"penetration_tester":    "penetration_tester — penetration testing, ethical hacking",
	"security_architect":    "security_architect — security architecture, design",
	"cryptographer":         "cryptographer — cryptography, encryption",
	"network_security":      "network_security — network security, protocols",
	"application_security":  "application_security — application security, secure coding",
	"cloud_security":        "cloud_security — cloud security, compliance",
	"devsecops":             "devsecops — DevSecOps, security automation",
	"IT_security":           "IT_security — IT security, infrastructure",
	"information_security":  "information_security — information security, policies",
	"database_security":     "database_security — database security, data protection",
	"privacy_expert":        "privacy_expert — privacy, GDPR, data protection",
	"compliance_security":   "compliance_security — compliance, security standards",
}

var domainSpecialistPresets = map[string][]string{
	"general":   {"planner", "researcher", "critic", "evaluator"},
	"legal":     {"planner", "legal_expert", "researcher", "critic", "evaluator"},
	"medical":   {"planner", "medical_expert", "researcher", "critic", "evaluator"},
	"education": {"planner", "educational_expert", "researcher", "creative_writer", "evaluator"},
	"finance":   {"planner", "financial_expert", "data_analyst", "researcher", "evaluator"},
	"creative":  {"planner", "creative_writer", "critic", "reflector", "evaluator"},
	"tech":      {"planner", "code_review", "qa_engineer", "devops_engineer", "architect"},
	"business":  {"planner", "product_manager", "financial_expert", "data_analyst", "evaluator"},
	"research":  {"planner", "researcher", "data_analyst", "critic", "evaluator"},
}

var collaborationTemplates = map[string]map[string][]string{
	"software_development": {
		"team":         {"architect", "backend_dev", "frontend_dev", "qa_engineer", "devops_engineer"},
		"workflow":     {"architect", "backend_dev", "frontend_dev", "qa_engineer", "devops_engineer"},
		"review_cycle": {"code_review", "security_expert", "qa_engineer"},
	},
	"product_design": {
		"team":         {"product_manager", "UX_researcher", "ux_designer", "UI_designer", "content_strategist"},
		"workflow":     {"UX_researcher", "ux_designer", "UI_designer", "product_manager"},
		"review_cycle": {"critic", "product_manager", "UX_researcher"},
	},
	"data_science": {
		"team":         {"data_scientist", "machine_learning", "data_analyst", "deep_learning", "AI_researcher"},
		"workflow":     {"data_scientist", "machine_learning", "data_analyst"},
		"review_cycle": {"evaluator", "data_scientist", "AI_researcher"},
	},
	"marketing": {
		"team":         {"marketing_expert", "content_strategist", "SEO_expert", "social_media", "copywriter"},
		"workflow":     {"content_strategist", "copywriter", "SEO_expert", "social_media"},
		"review_cycle": {"creative_writer", "marketing_expert", "critic"},
	},
	"research": {
		"team":         {"researcher", "scientist", "data_analyst", "AI_researcher", "critic"},
		"workflow":     {"researcher", "data_analyst", "scientist"},
		"review_cycle": {"critic", "evaluator", "researcher"},
	},
	"legal_compliance": {
		"team":         {"legal_expert", "lawyer", "compliance_officer", "privacy_expert", "auditor"},
		"workflow":     {"legal_expert", "compliance_officer", "privacy_expert"},
		"review_cycle": {"lawyer", "compliance_officer", "critic"},
	},
	"healthcare": {
		"team":         {"medical_expert", "doctor", "nurse", "pharmacist", "researcher"},
		"workflow":     {"medical_expert", "doctor", "pharmacist"},
		"review_cycle": {"doctor", "nurse", "evaluator"},
	},
	"education": {
		"team":         {"educational_expert", "teacher", "professor", "content_strategist", "creative_writer"},
		"workflow":     {"educational_expert", "teacher", "content_strategist"},
		"review_cycle": {"evaluator", "teacher", "critic"},
	},
	"finance": {
		"team":         {"financial_expert", "investment_advisor", "accountant", "risk_manager", "analyst"},
		"workflow":     {"financial_expert", "analyst", "risk_manager"},
		"review_cycle": {"investment_advisor", "accountant", "evaluator"},
	},
	"game_development": {
		"team":         {"game_designer", "game_programmer", "game_dev", "level_designer", "3D_artist"},
		"workflow":     {"game_designer", "level_designer", "game_programmer"},
		"review_cycle": {"critic", "game_designer", "qa_engineer"},
	},
	"video_production": {
		"team":         {"video_producer", "video_editor", "director", "colorist", "sound_designer"},
		"workflow":     {"director", "video_producer", "video_editor"},
		"review_cycle": {"critic", "director", "colorist"},
	},
	"security_operations": {
		"team":         {"security_expert", "cybersecurity_analyst", "penetration_tester", "security_architect", "devsecops"},
		"workflow":     {"security_architect", "security_expert", "penetration_tester"},
		"review_cycle": {"security_expert", "cybersecurity_analyst", "critic"},
	},
	"cloud_infrastructure": {
		"team":         {"cloud_engineer", "devops_engineer", "systems_admin", "network_engineer", "database_admin"},
		"workflow":     {"cloud_engineer", "devops_engineer", "database_admin"},
		"review_cycle": {"architect", "cloud_engineer", "qa_engineer"},
	},
	"content_creation": {
		"team":         {"creative_writer", "copywriter", "technical_writer", "editor", "graphic_designer"},
		"workflow":     {"creative_writer", "copywriter", "editor"},
		"review_cycle": {"editor", "critic", "creative_writer"},
	},
	"community_management": {
		"team":         {"community_manager", "social_media", "content_strategist", "moderator", "PR_specialist"},
		"workflow":     {"community_manager", "social_media", "content_strategist"},
		"review_cycle": {"PR_specialist", "critic", "community_manager"},
	},
	"startup_acceleration": {
		"team":         {"startup_advisor", "entrepreneur", "product_manager", "CTO", "marketing_expert"},
		"workflow":     {"startup_advisor", "product_manager", "CTO"},
		"review_cycle": {"entrepreneur", "critic", "evaluator"},
	},
	"ai_development": {
		"team":         {"AI_researcher", "machine_learning", "deep_learning", "data_scientist", "blockchain_dev"},
		"workflow":     {"AI_researcher", "machine_learning", "data_scientist"},
		"review_cycle": {"evaluator", "AI_researcher", "critic"},
	},
	"design_system": {
		"team":         {"ux_designer", "UI_designer", "graphic_designer", "typographer", "illustrator"},
		"workflow":     {"ux_designer", "UI_designer", "graphic_designer"},
		"review_cycle": {"critic", "UX_researcher", "ux_designer"},
	},
	"event_management": {
		"team":         {"event_planner", "project_manager", "marketing_expert", "PR_specialist", "copywriter"},
		"workflow":     {"event_planner", "project_manager", "marketing_expert"},
		"review_cycle": {"PR_specialist", "critic", "evaluator"},
	},
	"translation_localization": {
		"team":         {"translator", "localization", "interpreter", "translator_legal", "translator_medical"},
		"workflow":     {"translator", "localization", "interpreter"},
		"review_cycle": {"editor", "critic", "translator"},
	},
	"inkling_moe": {
		"team":         {"inkling_expert", "moe_specialist", "multimodal_engineer", "code_architect", "AI_agent"},
		"workflow":     {"inkling_expert", "moe_specialist", "multimodal_engineer"},
		"review_cycle": {"code_review", "security_expert", "evaluator"},
	},
}

func buildSpecialistDescriptions(specialistList []string) string {
	var descs []string
	for _, s := range specialistList {
		if desc, ok := allSpecialists[s]; ok {
			descs = append(descs, fmt.Sprintf("- %s", desc))
		}
	}
	return strings.Join(descs, "\n")
}
